BlockTechMVC/BlockTechMVC/Controllers/CriptomoedasHojeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlockTechMVC.Data;
using BlockTechMVC.Models;
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;

namespace BlockTechMVC.Controllers
{
    [Authorize]
    public class CriptomoedasHojeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CriptomoedasHojeController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Route("criptomoedas-valores")]
        // GET: CriptomoedasHoje
        public async Task<IActionResult> Index(DateTime searchDate, string sortOrder)
        {
            try
            {
                var criptomoedas = _context.CriptomoedaHoje
                    .Where(c => c.Data.Equals(DateTime.Now.Date))
                    .Include(c => c.Criptomoeda);

                if (searchDate != DateTime.MinValue)
                {
                    criptomoedas = _context.CriptomoedaHoje
                    .Where(c => c.Data.Equals(searchDate))
                    .Include(c => c.Criptomoeda);
                }

                ViewBag.NameSortParm = sortOrder == "Nome" ? "Nome_desc" : "Nome";
                ViewBag.ValueSortParm = sortOrder == "Valor" ? "Valor_desc" : "Valor";

                if (sortOrder != null)
                {
                    var criptomoeda = criptomoedas.OrderBy(c => c.Criptomoeda.Nome);
                    switch (sortOrder)
                    {
                        case "Nome_desc":
                            criptomoeda = criptomoedas.OrderByDescending(c => c.Criptomoeda.Nome);
                            break;
                        case "Valor_desc":
                            criptomoeda = criptomoedas.OrderByDescending(c => c.Valor);
                            break;
                        case "Valor":
                            criptomoeda = criptomoedas.OrderBy(c => c.Valor);
                            break;
                        case "Nome":
                            criptomoeda = criptomoedas.OrderBy(c => c.Criptomoeda.Nome);
                            break;
                        default:
                            criptomoeda = criptomoedas.OrderBy(c => c.Criptomoeda.Nome);
                            break;
                    }
                    return View(await criptomoeda.ToListAsync());
                }

                return View(await criptomoedas.ToListAsync());
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado. Tente novamente." });
            }
        }

        // GET: CriptomoedasHoje/Details/5
        [Route("criptomoedas-valores/detalhes")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Criptomoeda não encontrada!" });
            }

            var criptomoedaHoje = await _context.CriptomoedaHoje
                .Include(c => c.Criptomoeda)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (criptomoedaHoje == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Criptomoeda não encontrada!" });
            }

            return View(criptomoedaHoje);
        }

        // GET: CriptomoedasHoje/Create
        [Route("criptomoedas-valores/adicionar")]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CriptomoedaId"] = new SelectList(_context.Criptomoeda, "Id", "Nome");
            ViewData["CriptomoedaIdSimb"] = new SelectList(_context.Criptomoeda, "Id", "Simbolo");
            return View();
        }

        // POST: CriptomoedasHoje/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("criptomoedas-valores/adicionar")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Data,Valor,CriptomoedaId")] CriptomoedaHoje criptomoedaHoje)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(criptomoedaHoje);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "" });
            }
        }

        // GET: CriptomoedasHoje/Edit/5
        [Route("criptomoedas-valores/editar")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Criptomoeda não encontrada!" });
            }

            var criptomoedaHoje = await _context.CriptomoedaHoje.FindAsync(id);
            if (criptomoedaHoje == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Criptomoeda não encontrada!" });
            }

            ViewData["CriptomoedaId"] = new SelectList(_context.Criptomoeda, "Id", "Nome", criptomoedaHoje.CriptomoedaId);
            ViewData["CriptomoedaIdSimb"] = new SelectList(_context.Criptomoeda, "Id", "Simbolo");
            return View(criptomoedaHoje);
        }

        // POST: CriptomoedasHoje/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("criptomoedas-valores/editar")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Data,Valor,CriptomoedaId")] CriptomoedaHoje criptomoedaHoje)
        {
            if (id != criptomoedaHoje.Id)
            {
                return RedirectToAction(nameof(Error), new { message = "Criptomoeda não encontrada!" });
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(criptomoedaHoje);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CriptomoedaHojeExists(criptomoedaHoje.Id))
                    {
                        return RedirectToAction(nameof(Error), new { message = "Criptomoeda não encontrada!" });
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(criptomoedaHoje);
        }

        // GET: CriptomoedasHoje/Delete/5
        [Authorize(Roles = "Admin")]
        [Route("criptomoedas-valores/deletar")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Criptomoeda não encontrada!" });
            }

            var criptomoedaHoje = await _context.CriptomoedaHoje
                .Include(c => c.Criptomoeda)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (criptomoedaHoje == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Criptomoeda não encontrada!" });
            }

            return View(criptomoedaHoje);
        }

        // POST: CriptomoedasHoje/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [Route("criptomoedas-valores/deletar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var criptomoedaHoje = await _context.CriptomoedaHoje.FindAsync(id);
            _context.CriptomoedaHoje.Remove(criptomoedaHoje);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CriptomoedaHojeExists(int id)
        {
            return _context.CriptomoedaHoje.Any(e => e.Id == id);
        }

        public IActionResult Error(string message)
        {
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };

            return View(viewModel);
        }

        [Route("simulacao")]
        public IActionResult Simulacao(string searchString, int? Busca, int? BuscaVenda)
        {
            List<SelectListItem> itens = new List<SelectListItem>();
            SelectListItem item1 = new SelectListItem() { Text = "Bitcoin", Value = "1", Selected = true };
            SelectListItem item2 = new SelectListItem() { Text = "Ethereum", Value = "2", Selected = false };
            SelectListItem item3 = new SelectListItem() { Text = "Bitcoin Cash", Value = "3", Selected = false };
            SelectListItem item4 = new SelectListItem() { Text = "XRP", Value = "4", Selected = false };
            SelectListItem item5 = new SelectListItem() { Text = "PAX Gold", Value = "5", Selected = false };
            SelectListItem item6 = new SelectListItem() { Text = "Litecoin", Value = "6", Selected = false };
            itens.Add(item1);
            itens.Add(item2);
            itens.Add(item3);
            itens.Add(item4);
            itens.Add(item5);
            itens.Add(item6);

            ViewBag.Busca = itens;

BlockTechMVC/BlockTechMVC/Views/CriptomoedasHoje/Create.cshtml
@model BlockTechMVC.Models.CriptomoedaHoje

@{
    ViewData["Title"] = "Adicionar";
}
<br />
<h1>@ViewData["Title"]</h1>
<br />
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CriptomoedaId" class="control-label"></label>
                <select asp-for="CriptomoedaId" class="form-control" asp-items="ViewBag.CriptomoedaId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Adicionar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlockTechMVC/BlockTechMVC/Views/CriptomoedasHoje/Delete.cshtml
@model BlockTechMVC.Models.CriptomoedaHoje

@{
    ViewData["Title"] = "Deletar";
}
<br />
<h1>@ViewData["Title"]</h1>
<br />
<h3>Tem certeza que deseja deletar essa criptomoeda?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Criptomoeda.Simbolo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Criptomoeda.Simbolo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Criptomoeda.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Criptomoeda.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class="col-sm-10">
            R$ @Html.DisplayFor(model => model.Valor)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Deletar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

BlockTechMVC/BlockTechMVC/Views/CriptomoedasHoje/Details.cshtml
@model BlockTechMVC.Models.CriptomoedaHoje

@{
    ViewData["Title"] = "Detalhes";
}
<br />
<h1>@ViewData["Title"]</h1>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Criptomoeda.Simbolo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Criptomoeda.Simbolo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Criptomoeda.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Criptomoeda.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class="col-sm-10">
            R$ @Html.DisplayFor(model => model.Valor)
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> 
} |
    <a asp-action="Index">Voltar</a>
</div>

BlockTechMVC/BlockTechMVC/Views/CriptomoedasHoje/Edit.cshtml
@model BlockTechMVC.Models.CriptomoedaHoje

@{
    ViewData["Title"] = "Editar";
}
<br />
<h1>@ViewData["Title"]</h1>
<br />
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CriptomoedaId" class="control-label"></label>
                <select asp-for="CriptomoedaId" class="form-control" asp-items="ViewBag.CriptomoedaId"></select>
                <span asp-validation-for="CriptomoedaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlockTechMVC/BlockTechMVC/Views/CriptomoedasHoje/Index.cshtml
@model IEnumerable<BlockTechMVC.Models.CriptomoedaHoje>

@{
    ViewData["Title"] = "Criptomoedas";
}
<br />
<h1>@ViewData["Title"]</h1>
<br />
@if (User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create" class="btn btn-light">Adicionar</a>
    </p>
}

<form asp-controller="CriptomoedasHoje" asp-action="Index">
    <p>
        Data: <input type="date" name="SearchDate">
        <input type="submit" value="Filtrar" />
    </p>
</form>

<div class="table-responsive">
    <table class="table table-hover">
        <caption>Lista de Criptomoedas e seus valores</caption> 
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Data)
                </th>
                <th>
                    @Html.ActionLink("Nome", "Index", new { sortOrder = ViewBag.NameSortParm }, new { @class = "imgOrder" })
                </th>
                <th>
                    @Html.ActionLink("Valor", "Index", new { sortOrder = ViewBag.ValueSortParm }, new { @class = "imgOrder" })
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Data)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Criptomoeda.Nome)
                    </td>
                    <td>
                        R$ @Html.DisplayFor(modelItem => item.Valor)
                    </td>
                    <td style="white-space: nowrap">
                        @if (User.IsInRole("Admin"))
                        {
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-dark">Editar</a>
                        }
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-dark">Detalhes</a>
                        @if (User.IsInRole("Admin"))
                        {
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-dark">Deletar</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

BlockTechMVC/BlockTechMVC/Views/CriptomoedasHoje/Simulacao.cshtml
@{
    ViewData["Title"] = "Simulação";
    var total = ViewBag.Total + " " + ViewBag.Simbolo;
    var totalVenda = "R$" + ViewBag.TotalVenda;
}
<br />
<h1 class="text-center">@ViewData["Title"]</h1>
<br />
<div class="text-center d-flex justify-content-center flex-wrap">
    <div class="bg-light-d my-2">
        <form asp-controller="CriptomoedasHoje" asp-action="Simulacao" method="get">
            <br />
            <h3>Compra</h3>
            <p>
                Criptomoeda
                @Html.DropDownList("Busca", null, new
           {
               onchange = "document.location.href='/Simulacao?Busca='+this.value;"
           })
            </p>
            <p>
                Valor
                <input type="text" name="SearchString">
            </p>
            <p>
                <input type="submit" value="Simular" class="btn btn-dark" />
            </p>
            <br />
            <h4>Total</h4>
            <h5>@total</h5>
            <br />
        </form>
    </div>
    <div class="bg-light-d">
        <form asp-controller="CriptomoedasHoje" asp-action="Simulacao" method="get">
            <br />
            <h3>Venda</h3>
            <p>
                Criptomoeda
                @Html.DropDownList("BuscaVenda", null, new
           {
               onchange = "document.location.href='/Simulacao?BuscaVenda='+this.value;"
           })
            </p>
            <p>
                Quantidade
                <input type="text" name="SearchString">
            </p>
            <p>
                <input type="submit" value="Simular" class="btn btn-dark"/>
            </p>
            <br />
            <h4>Total</h4>
            <h5>@totalVenda</h5>
            <br />
        </form>
    </div>
</div>