BlockTechMVC/BlockTechMVC/Controllers/CriptomoedasController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BlockTechMVC.Data;
using BlockTechMVC.Models;
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;

namespace BlockTechMVC.Controllers
{
    //Controller apenas para ADM adicionar, remover e alterar Criptomoedas (nome e símbolo)

    [Authorize(Roles = "Admin")]
    public class CriptomoedasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CriptomoedasController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Route("criptomoedas")]
        // GET: Criptomoedas
        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
            ViewBag.NameSortParm =  sortOrder == "Nome" ? "Nome_desc" : "Nome";

            var criptomoedas = from c in _context.Criptomoeda
                               select c;

            switch (sortOrder)
            {
                case "Nome_desc":
                    criptomoedas = criptomoedas.OrderByDescending(s => s.Nome);
                    break;    
                default:
                    criptomoedas = criptomoedas.OrderBy(s => s.Nome);
                    break;
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                criptomoedas = criptomoedas.Where(c => c.Nome.Contains(searchString));
            }

            return View(await criptomoedas.ToListAsync());
        }
     
        [Route("criptomoedas/detalhes")]
        // GET: Criptomoedas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id não encontrado!" });
            }

            var criptomoeda = await _context.Criptomoeda
                .FirstOrDefaultAsync(m => m.Id == id);
            if (criptomoeda == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id não encontrado!" });
            }

            return View(criptomoeda);
        }

        [Route("criptomoedas/adicionar")]
        // GET: Criptomoedas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Criptomoedas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Simbolo,Cadastro")] Criptomoeda criptomoeda)
        {
            if (_context.Criptomoeda.Any(c => c.Nome == criptomoeda.Nome)) return RedirectToAction(nameof(Error), new { message = "Criptomoeda já cadastrada!" });
            if (_context.Criptomoeda.Any(c => c.Simbolo == criptomoeda.Simbolo)) return RedirectToAction(nameof(Error), new { message = "Criptomoeda já cadastrada!" });

            if (ModelState.IsValid)
            {
                _context.Add(criptomoeda);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(criptomoeda);
        }

        [Route("criptomoedas/editar")]
        // GET: Criptomoedas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id não encontrado!" });
            }

            var criptomoeda = await _context.Criptomoeda.FindAsync(id);
            if (criptomoeda == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id não encontrado!" });
            }
            return View(criptomoeda);
        }

        [Route("criptomoedas/editar")]
        // POST: Criptomoedas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Simbolo,Cadastro")] Criptomoeda criptomoeda)
        {
            if (id != criptomoeda.Id)
            {
                return RedirectToAction(nameof(Error), new { message = "Id não encontrado!" });
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(criptomoeda);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CriptomoedaExists(criptomoeda.Id))
                    {
                        return RedirectToAction(nameof(Error), new { message = "Criptomoeda não encontrada!" });
                    }
                    else
                    {
                        return RedirectToAction(nameof(Error), new { message = "" });
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(criptomoeda);
        }

        private bool CriptomoedaExists(int id)
        {
            return _context.Criptomoeda.Any(e => e.Id == id);
        }

        public IActionResult Error(string message)
        {
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier 
            };

            return View(viewModel);
        }
    }

}

BlockTechMVC/BlockTechMVC/Controllers/RelatoriosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using BlockTechMVC.Data;
using Microsoft.AspNetCore.Authorization;
using BlockTechMVC.Models;
using System.Diagnostics;

namespace BlockTechMVC.Controllers
{
    [Authorize]
    public class RelatoriosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RelatoriosController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Route("relatorios")]
        // GET: Relatorios
        public ActionResult Index()
        {
            try { 
            ViewBag.Bitcoin = CriptomoedaHoje("Bitcoin").ToString("F4");
            ViewBag.Ethereum = CriptomoedaHoje("Ethereum").ToString("F4");
            ViewBag.BitcoinCash = CriptomoedaHoje("Bitcoin Cash").ToString("F4");
            ViewBag.XRP = CriptomoedaHoje("XRP").ToString("F4");
            ViewBag.PaxGold = CriptomoedaHoje("PAX Gold").ToString("F4");
            ViewBag.Litecoin = CriptomoedaHoje("Litecoin").ToString("F4");

            return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("relatorios/bitcoin")]
        public ActionResult Bitcoin()
        {
            try
            {
                ViewBag.Dias = Ultimos7Dias();
                ViewBag.Valores = Valores7Dias("Bitcoin");

                return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("relatorios/bitcoin-mes")]
        public ActionResult Bitcoin30()
        {
            try
            {
                ViewBag.Dias = Ultimos30Dias();
                ViewBag.Valores = Valores30Dias("Bitcoin");

                return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("relatorios/ethereum")]
        public ActionResult Ethereum()
        {
            try { 
            ViewBag.Dias = Ultimos7Dias();
            ViewBag.Valores = Valores7Dias("Ethereum");

            return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("relatorios/ethereum-mes")]
        public ActionResult Ethereum30()
        {
            try { 
            ViewBag.Dias = Ultimos30Dias();
            ViewBag.Valores = Valores30Dias("Ethereum");

            return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("relatorios/bitcoin-cash")]
        public ActionResult BitcoinCash()
        {
            try { 
            ViewBag.Dias = Ultimos7Dias();
            ViewBag.Valores = Valores7Dias("Bitcoin Cash");

            return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("relatorios/bitcoin-cash-mes")]
        public ActionResult BitcoinCash30()
        {
            try {
            ViewBag.Dias = Ultimos30Dias();
            ViewBag.Valores = Valores30Dias("Bitcoin Cash");

            return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("relatorios/xrp")]
        public ActionResult Xrp()
        {
            try { 
            ViewBag.Dias = Ultimos7Dias();
            ViewBag.Valores = Valores7Dias("XRP");

            return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("relatorios/xrp-mes")]
        public ActionResult Xrp30()
        {
            try { 
            ViewBag.Dias = Ultimos30Dias();
            ViewBag.Valores = Valores30Dias("XRP");

            return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("relatorios/pax-gold")]
        public ActionResult PaxGold()
        {
            try { 
            ViewBag.Dias = Ultimos7Dias();
            ViewBag.Valores = Valores7Dias("PAX Gold");

            return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("relatorios/pax-gold-mes")]
        public ActionResult PaxGold30()
        {
            try { 
            ViewBag.Dias = Ultimos30Dias();
            ViewBag.Valores = Valores30Dias("PAX Gold");

            return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("relatorios/litecoin")]
        public ActionResult Litecoin()
        {
            try { 
            ViewBag.Dias = Ultimos7Dias();
            ViewBag.Valores = Valores7Dias("Litecoin");

            return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("relatorios/litecoin-mes")]
        public ActionResult Litecoin30()
        {
            try { 
            ViewBag.Dias = Ultimos30Dias();
            ViewBag.Valores = Valores30Dias("Litecoin");

            return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("relatorios/semanal")]
        public IActionResult Semanal()
        {
            try
            {
                ViewBag.Dias = Ultimos7Dias();
                ViewBag.Bitcoin = Porcentagem("Bitcoin");
                ViewBag.Ethereum = Porcentagem("Ethereum");
                ViewBag.BitcoinCash = Porcentagem("Bitcoin Cash");
                ViewBag.XRP = Porcentagem("XRP");
                ViewBag.PaxGold = Porcentagem("PAX Gold");
                ViewBag.Litecoin = Porcentagem("Litecoin");

                return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("relatorios/mensal")]
        public IActionResult Mensal()
        {
            try
            {
                ViewBag.Dias = Ultimos30Dias();
                ViewBag.Bitcoin = PorcentagemTrinta("Bitcoin");
                ViewBag.Ethereum = PorcentagemTrinta("Ethereum");
                ViewBag.BitcoinCash = PorcentagemTrinta("Bitcoin Cash");
                ViewBag.XRP = PorcentagemTrinta("XRP");
                ViewBag.PaxGold = PorcentagemTrinta("PAX Gold");
                ViewBag.Litecoin = PorcentagemTrinta("Litecoin");
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        private double CriptomoedaHoje(string nome)
        {
            var criptomoeda = (from coin in _context.Criptomoeda
                               join criptohoje in _context.CriptomoedaHoje
                               on coin.Id equals criptohoje.CriptomoedaId
                               where coin.Nome == nome && criptohoje.Data == DateTime.Today
                               select criptohoje.Valor).Single();

            return criptomoeda;
        }

        private List<int> Ultimos7Dias()
        {
            var diasList = new List<int>();

            DateTime diasSete = DateTime.Today;

            for (int i = 7; i >= 0; i--)
            {
                diasSete = DateTime.Today;
                diasSete = diasSete.AddDays(-i);
                diasList.Add(diasSete.Day);
            }
            return diasList;
        }

        private List<int> Ultimos30Dias()
        {
            var diasList = new List<int>();

            DateTime diasTrinta = DateTime.Today;

            for (int i = 30; i >= 0; i--)
            {
                diasTrinta = DateTime.Today;
                diasTrinta = diasTrinta.AddDays(-i);
                diasList.Add(diasTrinta.Day);
            }
            return diasList;
        }

        private List<double> Valores7Dias(string nome)
        {
            var valorList = new List<double>();

            for (int i = 7; i >= 0; i--)
            {
                DateTime diasSete = DateTime.Today;

BlockTechMVC/BlockTechMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlockTech</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="shortcut icon" href="~/Icon/logo.ico" type="image/x-icon" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logoMin.png" width="50" alt="Logo da BlockTech"/>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                      @if (User?.Identity.IsAuthenticated == true)
                      {
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Criptomoedas" asp-action="Index">Criptomoedas</a>
                            </li>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="CriptomoedasHoje" asp-action="Index">Tempo Real</a>
                            </li>
                        }
                        @if (!User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="CriptomoedasHoje" asp-action="Index">Criptomoedas</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Transacoes" asp-action="Index">Transações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="ContasClientes" asp-action="Index">Conta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="ContasClientes" asp-action="Aplicacoes">Aplicações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Relatorios" asp-action="Index">Relatórios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="MeusInvestimentos" asp-action="Index">Investimentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="CriptomoedasHoje" asp-action="Simulacao">Simulação</a>
                        </li>

                      }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BlockTech 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>