BlockTechMVC/BlockTechMVC/Controllers/ContasClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlockTechMVC.Data;
using BlockTechMVC.Models;
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;

namespace BlockTechMVC.Controllers
{
    [Authorize]
    public class ContasClientesController : CoreController
    {
        private readonly ApplicationDbContext _context;

        public ContasClientesController(ApplicationDbContext context) : base(context)
        {
            _context = context;
        }

        [Route("conta")]
        // GET: ContasClientes
        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
            var user = User.Identity.Name;
            try
            {
                ViewBag.Total = SaldoTotal(user);

                if (user == "Administrador")
                {
                    double[] usuarios = new double[20];
                    int i = 0;
                    foreach (var item in _context.Saldo)
                    {
                        var usuario = (from c in _context.Saldo
                                       join conta in _context.ContaCliente
                                       on c.ContaClienteId equals conta.Id
                                       join cliente in _context.ApplicationUser
                                       on conta.ApplicationUserID equals cliente.Id
                                       where item.ContaClienteId == conta.Id
                                       select cliente.UserName).FirstOrDefault();
                        var saldo = SaldoTotal(usuario);

                        usuarios[i] = saldo;
                        i++;
                    }
                    ViewBag.TotalAdm = usuarios.ToList();
                }

                if (user == "Administrador")
                {
                    ViewBag.NameSortParm = sortOrder == "Nome" ? "Nome_desc" : "Nome";

                    var application = _context.Saldo
                        .Include(t => t.ContaCliente)
                        .Include(t => t.ContaCliente.ApplicationUser);

                    if (sortOrder != null)
                    {
                        var usuario = application.OrderBy(c => c.ContaCliente.ApplicationUser.Nome);

                        switch (sortOrder)
                        {
                            case "Nome":
                                usuario = application.OrderBy(c => c.ContaCliente.ApplicationUser.Nome);
                                break;
                            case "Nome_desc":
                                usuario = application.OrderByDescending(c => c.ContaCliente.ApplicationUser.Nome);
                                break;
                            default:
                                usuario = application.OrderByDescending(c => c.ContaCliente.ApplicationUser.Nome);
                                break;
                        }

                        return View(await usuario.ToListAsync());
                    }

                    if (!String.IsNullOrEmpty(searchString))
                    {
                        var usuarioSelecionado = _context.Saldo
                       .Include(t => t.ContaCliente)
                       .Include(t => t.ContaCliente.ApplicationUser)
                       .Where(t => t.ContaCliente.ApplicationUser.Nome.Contains(searchString));

                        return View(usuarioSelecionado.ToList());
                    }

                    return View(await application.ToListAsync());
                }
                else
                {
                    var usuario = _context.Saldo
                          .Include(t => t.ContaCliente)
                          .Include(t => t.ContaCliente.ApplicationUser)
                          .Where(t => t.ContaCliente.ApplicationUser.UserName == user);

                    return View(await usuario.ToListAsync());
                }
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Error), new { message = "Ocorreu um erro inesperado! Tente novamente em alguns instantes." });
            }
        }

        [Route("conta/detalhes")]
        // GET: ContasClientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var user = User.Identity.Name;

            var usuario = (from c in _context.Saldo
                           join conta in _context.ContaCliente
                           on c.ContaClienteId equals conta.Id
                           join cliente in _context.ApplicationUser
                           on conta.ApplicationUserID equals cliente.Id
                           where c.Id == id
                           select cliente.UserName).FirstOrDefault();
            ViewBag.TotalAdm = SaldoTotal(usuario);


            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Transação não encontrada!" });
            }

            var transacao = await _context.Transacao
                .Include(t => t.ContaCliente)
                .Include(t => t.CriptoSaldo)
                .Include(t => t.CriptomoedaHoje)
                .Include(t => t.ContaCliente.Conta)
                .Include(t => t.ContaCliente.ApplicationUser)
                .Include(t => t.Saldo)
                .FirstOrDefaultAsync(m => m.Saldo.Id == id);

            if (transacao == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Transação não encontrada!" });
            }

            ViewData["ContaVinculada"] = "Conta Vinculada";
            ViewBag.Total = SaldoTotal(user);

            return View(transacao);
        }

        private bool TransacaoExists(int id)
        {
            return _context.Transacao.Any(e => e.Id == id);
        }

        [Route("aplicacoes")]
        public async Task<IActionResult> Aplicacoes(int? id, string searchString, int? Busca, string sortOrder)
        {
            var user = User.Identity.Name;

            ViewBag.Quantidade = sortOrder == "Quantidade" ? "Quantidade_desc" : "Quantidade";
            ViewBag.Criptomoeda = sortOrder == "Criptomoeda" ? "Criptomoeda_desc" : "Criptomoeda";

            if (user == "Administrador")
            {
                ViewBag.Nome = sortOrder == "Nome" ? "Nome_desc" : "Nome";

                List<SelectListItem> itens = new List<SelectListItem>();
                SelectListItem item1 = new SelectListItem() { Text = "Nome/Razão Social", Value = "1", Selected = true };
                SelectListItem item2 = new SelectListItem() { Text = "Criptomoeda", Value = "2", Selected = false };
                itens.Add(item1);
                itens.Add(item2);

                ViewBag.Busca = itens;

                var applicationDbContext = _context.CriptoSaldo
                    .Include(t => t.ContaCliente)
                    .Include(t => t.ContaCliente.ApplicationUser);

                if (sortOrder != null)
                {
                    var orderName = applicationDbContext.OrderBy(t => t.ContaCliente.ApplicationUser.Nome);

                    switch (sortOrder)
                    {
                        case "Nome_desc":
                            orderName = orderName.OrderByDescending(s => s.ContaCliente.ApplicationUser.Nome);
                            break;
                        case "Nome":
                            orderName = applicationDbContext.OrderBy(s => s.ContaCliente.ApplicationUser.Nome);
                            break;
                        case "Quantidade":
                            orderName = applicationDbContext.OrderBy(s => s.Quantidade);
                            break;
                        case "Quantidade_desc":
                            orderName = applicationDbContext.OrderByDescending(s => s.Quantidade);
                            break;
                        case "Criptomoeda":
                            orderName = applicationDbContext.OrderBy(s => s.Criptomoeda);
                            break;
                        case "Criptomoeda_desc":
                            orderName = applicationDbContext.OrderByDescending(s => s.Criptomoeda);
                            break;
                        default:
                            orderName = applicationDbContext.OrderBy(s => s.ContaCliente.ApplicationUser.Nome);
                            break;
                    };
                    return View(orderName.ToList());
                }

                if (Busca != null)
                {
                    itens.Where(i => i.Value == Busca.ToString()).First().Selected = true;
                }
                if (Busca == 1)
                {
                    if (!String.IsNullOrEmpty(searchString))
                    {
                        var usuarioSelecionado = _context.CriptoSaldo
                        .Include(t => t.ContaCliente)
                        .Include(t => t.ContaCliente.ApplicationUser)
                        .Where(t => t.ContaCliente.ApplicationUser.Nome.Contains(searchString));

                        return View(usuarioSelecionado.ToList());
                    }
                }
                if (Busca == 2)
                {
                    if (!String.IsNullOrEmpty(searchString))
                    {
                        var usuarioSelecionado = _context.CriptoSaldo
                       .Include(t => t.ContaCliente)
                       .Include(t => t.ContaCliente.ApplicationUser)
                       .Where(t => t.Criptomoeda.Contains(searchString));

                        return View(usuarioSelecionado.ToList());
                    }
                }

                return View(await applicationDbContext.ToListAsync());
            }

BlockTechMVC/BlockTechMVC/Views/ContasClientes/Aplicacoes.cshtml
@model IEnumerable<BlockTechMVC.Models.CriptoSaldo>

@{
    ViewData["Title"] = "Aplicações";
}

<br />
<h1>@ViewData["Title"]</h1>
<br />
@if (User.IsInRole("Admin"))
{
    <form asp-controller="ContasClientes" asp-action="Aplicacoes" method="get">
        <p>
            @Html.DropDownList("Busca", null, new
            {
           onchange = "document.location.href='/aplicacoes?Busca='+this.value;"
            })

            <input type="text" name="SearchString">
            <input type="submit" value="Filtrar" />
        </p>
    </form>
}
else
{
    <form asp-controller="ContasClientes" asp-action="Aplicacoes" method="get">
        <p>
            Criptomoeda:
            <input type="text" name="SearchString">
            <input type="submit" value="Filtrar" />
        </p>
    </form>
}


<div class="table-responsive">
    <table class="table">
        <caption>Lista de Aplicações</caption>
        <thead>
            <tr>
                @if (User.IsInRole("Admin"))
                {
                    <th>
                        @Html.ActionLink("Nome", "Aplicacoes", new { sortOrder = ViewBag.Nome }, new { @class = "imgOrder" })
                    </th>
                }
                <th>
                    @Html.ActionLink("Criptomoeda", "Aplicacoes", new { sortOrder = ViewBag.Criptomoeda }, new { @class = "imgOrder" })
                </th>
                <th>
                    @Html.ActionLink("Quantidade", "Aplicacoes", new { sortOrder = ViewBag.Quantidade }, new { @class = "imgOrder" })
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    @if (User.IsInRole("Admin"))
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.ContaCliente.ApplicationUser.Nome)
                        </td>
                    }
                    <td>
                        @Html.DisplayFor(modelItem => item.Criptomoeda)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantidade)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

BlockTechMVC/BlockTechMVC/Views/ContasClientes/Details.cshtml
@model BlockTechMVC.Models.Transacao

@{
    ViewData["Title"] = "Detalhes";
    var total = ViewBag.Total;
    var totalAdm = ViewBag.TotalAdm;
}
<br />
<h1>@ViewData["Title"]</h1>
<br />
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContaCliente.DataAbertura)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContaCliente.DataAbertura)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContaCliente.ApplicationUser.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContaCliente.ApplicationUser.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContaCliente.NumeroConta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContaCliente.NumeroConta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Saldo.SaldoAtualRS)
        </dt>
        @if (User.IsInRole("Admin"))
        {
    <dd class="col-sm-10">
        R$ @totalAdm
    </dd>
        }
        else
        {
            <dd class="col-sm-10">
                R$ @total
            </dd>
        }
        <div style="white-space:pre-line; font-weight: bold; font-size:larger" class="col-sm-12">
            @ViewBag.ContaVinculada
        </div>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContaCliente.Conta.Banco)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContaCliente.Conta.Banco)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContaCliente.Conta.Agencia)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContaCliente.Conta.Agencia)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContaCliente.Conta.TipoConta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContaCliente.Conta.TipoConta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContaCliente.Conta.NumeroConta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContaCliente.Conta.NumeroConta)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Voltar</a>
</div>

BlockTechMVC/BlockTechMVC/Views/ContasClientes/Index.cshtml
@model IEnumerable<BlockTechMVC.Models.Saldo>

@{
    ViewData["Title"] = "Conta";
    var total = ViewBag.Total;

    int i = 0;

    double[] totalGeral = new double[20];

    if (User.IsInRole("Admin")) {
        foreach (var item in ViewBag.TotalAdm)
        {
            totalGeral[i] = item;
            i++;
        }
        i = 0;
    }
}

@if (!User.IsInRole("Admin"))
{
    <h1>@ViewData["Title"]</h1>
    <br />
}
@if (User.IsInRole("Admin"))
{
    <br />
    <h1>Contas</h1>
    <br />
    <form asp-controller="ContasClientes" asp-action="Index" method="get">
        <p>
            Nome/Razão Social: <input type="text" name="SearchString">
            <input type="submit" value="Filtrar" />
        </p>
    </form>
}

<div class="table-responsive">
    <table class="table table-hover">
        @if (User.IsInRole("Admin"))
        {
            <caption>Informações das Contas</caption>
        }
        else
        {
            <caption>Informações da Conta</caption>
        }

        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ContaCliente.DataAbertura)
                </th>
                @if (User.IsInRole("Admin"))
                {
                    <th>
                        @Html.ActionLink("Nome", "Index", new { sortOrder = ViewBag.NameSortParm }, new { @class = "imgOrder" })
                    </th>
                }
                <th>
                    @Html.DisplayNameFor(model => model.ContaCliente.NumeroConta)
                </th>
                @if (User.IsInRole("Admin"))
                {
            <th>
                @Html.DisplayNameFor(model => model.SaldoAtualRS)
            </th>
                }
                else
                {
                    <th>
                        @Html.DisplayNameFor(model => model.SaldoAtualRS)
                    </th>
                }

                <th></th>
                <th style="white-space: nowrap"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ContaCliente.DataAbertura)
                    </td>
                    @if (User.IsInRole("Admin"))
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.ContaCliente.ApplicationUser.Nome)
                        </td>
                    }
                    <td>
                        @Html.DisplayFor(modelItem => item.ContaCliente.NumeroConta)
                    </td>
                    @if (User.IsInRole("Admin"))
                    {
                        <td>
                            @totalGeral[i]
                            @{ i++; }
                        </td>
                    }
                    else
                    {
                        <td>
                            R$ @total
                        </td>
                    }
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-dark">Detalhes</a>
                    </td>
                </tr>

            }
        </tbody>
    </table>
</div>